apiVersion: apps/v1
kind: Deployment
metadata:
    name: worker-deployment
spec:
    selector:
        matchLabels:
            component: worker
    replicas: 1
    template:
        metadata:
            labels:
                component: worker
        spec:
            containers:
                - name: worker
                  image: samnoh/multi-worker
                  imagePullPolicy: Never
                  env:
                      - name: REDIS_HOST
                        value: redis-cluster-ip-service
                      - name: REDIS_PORT
                        value: "6379"
                  resources:
                      requests:
                          cpu: 100m
                          memory: 100Mi
                      limits:
                          cpu: 150m
                          memory: 150Mi
